version: '3.8'

services:
  # RabbitMQ Service
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"   # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management UI
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword

  # Order Service
  order-service:
    image: "serpild/order-service"
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_CONNECTION_STRING=amqp://myuser:mypassword@rabbitmq:5672/
      - PORT=3000
    depends_on:
      - rabbitmq

  # Product Service
  product-service:
    image: "serpild/product-service"
    ports:
      - "3030:3030"
    environment:
      - PORT=3030

  # Store Front (Frontend Service)
  store-front:
    image: "serpild/store-front"
    ports:
      - "80:80"
    environment:
      - VUE_APP_ORDER_SERVICE_URL=http://order-service:3000
      - VUE_APP_PRODUCT_SERVICE_URL=http://product-service:3030
    depends_on:
      - order-service
      - product-service

  # AI Service
  ai-service:
    image: "serpild/ai-service"
    ports:
      - "4000:4000" # Specify the correct port if needed
    environment:
      - PORT=4000

  # Makeline Service
  makeline-service:
    image: "serpild/makeline-service"
    ports:
      - "5001:5000" # Specify the correct port if needed
    environment:
      - PORT=5000

  # Virtual Worker Service
  virtual-worker:
    image: "serpild/virtual-worker"
    ports:
      - "6000:6000" # Specify the correct port if needed
    environment:
      - PORT=6000

  # Virtual Customer Service
  virtual-customer:
    image: "serpild/virtual-customer"
    ports:
      - "7100:7000" # Specify the correct port if needed
    environment:
      - PORT=7000

  # Store Admin Service
  store-admin:
    image: "serpild/store-admin"
    ports:
      - "8080:8080" # Specify the correct port if needed
    environment:
      - PORT=8080
