version: '3'

services:
  # RabbitMQ service definition
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"   # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management plugin UI port
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword

  # Virtual Worker service definition
  virtual-worker:
    image: serpild/virtual-worker:latest
    container_name: virtual-worker-container
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq

  # Virtual Customer service definition
  virtual-customer:
    image: serpild/virtual-customer:latest
    container_name: virtual-customer-container
    ports:
      - "8082:8080"
    depends_on:
      - rabbitmq

  # Makeline Service definition
  makeline-service:
    image: serpild/makeline-service:latest
    container_name: makeline-service-container
    ports:
      - "8083:8080"
    depends_on:
      - rabbitmq

  # AI Service definition
  ai-service:
    image: serpild/ai-service:latest
    container_name: ai-service-container
    ports:
      - "8084:8080"
    depends_on:
      - rabbitmq

  # Store Admin Service definition
  store-admin:
    image: serpild/store-admin:latest
    container_name: store-admin-container
    ports:
      - "8085:8080"
    depends_on:
      - rabbitmq

  # Order Service definition
  order-service:
    build: ./order-service-L4
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_CONNECTION_STRING=amqp://myuser:mypassword@rabbitmq:5672/
      - PORT=3000
    depends_on:
      - rabbitmq

  # Product Service definition
  product-service:
    build: ./product-service-python-L4
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
    depends_on:
      - rabbitmq

  # Store Front (Frontend) service definition
  store-front:
    build: ./store-front-L4
    ports:
      - "80:80"
    environment:
      - VUE_APP_ORDER_SERVICE_URL=http://order-service:3000
      - VUE_APP_PRODUCT_SERVICE_URL=http://product-service:3030
    depends_on:
      - product-service
      - order-service
